### ISSUE TITLE
Getting an error when deploying

### ISSUE THREAD

**Issue by BenRoche** [tiaanswart/LightningFieldset#1]
Hi,

i get the following error when deploying

Failures:
objects/Account.object(16,26):In field: Account_Type__c - no CustomField named Account.Account_Type__c found
classes/FieldsetController.cls(67,70):Method does not exist or incorrect signature: void getLabel() from the type FieldSet
classes/FieldsetController.cls(72,82):Method does not exist or incorrect signature: void getFields() from the type FieldSet
classes/FieldsetController.cls(74,55):Method does not exist or incorrect signature: void getFieldPath() from the type FieldSetMember
classes/FieldsetControllerTest.cls(61,35):Dependent class is invalid and needs recompilation:
 Class FieldsetController : Illegal assignment from Map to Map
lwc/fieldset/fieldset.js(fieldset):Unable to find Apex action class referenced as 'FieldsetController'.
classes/FieldsetController.cls(61,35):Illegal assignment from Map to Map

**Comment by BenRoche** [comment]
After creating the 2 custom fields, i still get
Failures:
classes/FieldsetController.cls(61,35):Illegal assignment from Map to Map
classes/FieldsetController.cls(67,70):Method does not exist or incorrect signature: void getLabel() from the type FieldSet
classes/FieldsetController.cls(72,82):Method does not exist or incorrect signature: void getFields() from the type FieldSet
classes/FieldsetController.cls(74,55):Method does not exist or incorrect signature: void getFieldPath() from the type FieldSetMember
classes/FieldsetControllerTest.cls(61,35):Dependent class is invalid and needs recompilation:
 Class FieldsetController : Illegal assignment from Map to Map
lwc/fieldset/fieldset.js(fieldset):Unable to find Apex action class referenced as 'FieldsetController'.

**Comment by tiaanswart** [comment]
Hello @BenRoche,
Thanks for reporting the Custom Fields issue. I have fixed that.
I tested the deployment to a developer org and it successfully deployed.
Cheers,
Tiaan
